Repository eclipse-daanse/org.eclipse.daanse.board.app, pull requests merged in 2025-04, with the labels that each got.

#89 Add connection repo with proper tests
  packages/lib/repository/connection/__tests__/test.test.ts
  packages/lib/repository/connection/package.json
  packages/lib/repository/connection/src/classes/index.ts
  packages/lib/repository/connection/src/index.ts
  packages/lib/repository/connection/tsconfig.json
  packages/lib/repository/connection/vite.config.ts
  yarn.lock
Labels: enhancement

#95 Restore rest datasource functionality. Add test for rest datasource. Fix for datasource factory.
  packages/lib/datasource/rest/__tests__/test.test.js
  packages/lib/datasource/rest/__tests__/test.test.ts
  packages/lib/datasource/rest/package.json
  packages/lib/datasource/rest/src/classes/index.ts
  packages/lib/factory/datasource/src/classes/index.ts
Labels: enhancement

#96 Restore rss datasource
  packages/lib/datasource/rss/__tests__/test.test.js
  packages/lib/datasource/rss/__tests__/test.test.ts
  packages/lib/datasource/rss/package.json
  packages/lib/datasource/rss/src/classes/index.ts
Labels: enhancement

#97 Restore csv datasource
  packages/lib/datasource/csv/__tests__/test.test.js
  packages/lib/datasource/csv/__tests__/test.test.ts
  packages/lib/datasource/csv/package.json
  packages/lib/datasource/csv/src/classes/index.ts
Labels: enhancement

#98 Restore graphql datasource
  packages/lib/datasource/graphql/__tests__/test.test.js
  packages/lib/datasource/graphql/__tests__/test.test.ts
  packages/lib/datasource/graphql/package.json
  packages/lib/datasource/graphql/src/classes/index.ts
Labels: enhancement

#115 Add widget repository
  packages/lib/repository/widget/package.json
  packages/lib/repository/widget/src/classes/index.ts
  packages/lib/repository/widget/src/index.ts
  packages/lib/repository/widget/tsconfig.json
  packages/lib/repository/widget/vite.config.ts
Labels: enhancement

#116 Add widget wrapper
  packages/ui/vue/widget/wrapper/package.json
  packages/ui/vue/widget/wrapper/src/WidgetWrapper.vue
  packages/ui/vue/widget/wrapper/src/index.ts
  packages/ui/vue/widget/wrapper/tsconfig.json
  packages/ui/vue/widget/wrapper/vite.config.ts
Labels: enhancement

#133 Add video widget
  packages/ui/vue/widget/video/package.json
  packages/ui/vue/widget/video/src/VideoWidget.vue
  packages/ui/vue/widget/video/src/VideoWidgetSettings.vue
  packages/ui/vue/widget/video/src/assets/video.svg
  packages/ui/vue/widget/video/src/index.ts
  packages/ui/vue/widget/video/tsconfig.json
  packages/ui/vue/widget/video/vite.config.ts
Labels: enhancement

#135 Add repeatable svg widget
  packages/ui/vue/widget/svg/repeat/package.json
  packages/ui/vue/widget/svg/repeat/src/RepeatableSvgWidget.vue
  packages/ui/vue/widget/svg/repeat/src/RepeatableSvgWidgetSettings.vue
  packages/ui/vue/widget/svg/repeat/src/assets/repeatable_svg.svg
  packages/ui/vue/widget/svg/repeat/src/index.ts
  packages/ui/vue/widget/svg/repeat/tsconfig.json
  packages/ui/vue/widget/svg/repeat/vite.config.ts
  yarn.lock
Labels: enhancement

#136 Add text widget
  packages/ui/vue/widget/text/plain/package.json
  packages/ui/vue/widget/text/plain/src/TextWidget.vue
  packages/ui/vue/widget/text/plain/src/TextWidgetSettings.vue
  packages/ui/vue/widget/text/plain/src/assets/text.svg
  packages/ui/vue/widget/text/plain/src/index.ts
  packages/ui/vue/widget/text/plain/tsconfig.json
  packages/ui/vue/widget/text/plain/vite.config.ts
Labels: enhancement

#140 Create dependabot.yml
  .github/dependabot.yml
Labels: documentation, enhancement, good first issue, dependencies, javascript

#156 Rework sample widget. Add datasourceRepository composable.
  packages/ui/vue/composables/package.json
  packages/ui/vue/composables/src/index.ts
  packages/ui/vue/composables/src/useDatasourceRepository.ts
  packages/ui/vue/composables/tsconfig.json
  packages/ui/vue/composables/vite.config.ts
  packages/ui/vue/widget/sample/package.json
  packages/ui/vue/widget/sample/src/SampleWidget.vue
  packages/ui/vue/widget/sample/src/SampleWidgetSettings.vue
  packages/ui/vue/widget/sample/src/assets/sample.svg
  packages/ui/vue/widget/sample/src/index.ts
  packages/ui/vue/widget/sample/src/types.d.ts
  packages/ui/vue/widget/sample/tsconfig.json
  packages/ui/vue/widget/sample/vite.config.ts
Labels: enhancement

#166 add riscv64 to docker build ci
  .github/workflows/docker_build.yml
Labels: enhancement

#174 daanse action
  .github/workflows/pr_run_daanse.yml
Labels: enhancement

#171 add cueMarker and snapshot generation
  .gitignore
  e2e/tsconfig.json
  e2e/vue.spec.ts
  packages/app/default/e2e/tsconfig.json
  packages/app/default/e2e/vue.spec.ts
  packages/app/default/playwright.config.ts
  packages/app/default/src/App.vue
  playwright.config.ts
  tools/test/screenshoter/screenshoter.ts
Labels: enhancement, daanse-requested

#170 Add chart widget
  packages/ui/vue/widget/chart/package.json
  packages/ui/vue/widget/chart/src/ChartWidget.vue
  packages/ui/vue/widget/chart/src/ChartWidgetSettings.vue
  packages/ui/vue/widget/chart/src/assets/chart.svg
  packages/ui/vue/widget/chart/src/index.ts
  packages/ui/vue/widget/chart/tsconfig.json
  packages/ui/vue/widget/chart/vite.config.ts
Labels: daanse-requested

#176 Add pivot table widget
  packages/ui/vue/widget/table/pivot/package.json
  packages/ui/vue/widget/table/pivot/src/PivotTableWidget.vue
  packages/ui/vue/widget/table/pivot/src/PivotTableWidgetSettings.vue
  packages/ui/vue/widget/table/pivot/src/assets/pivot_table.svg
  packages/ui/vue/widget/table/pivot/src/components/Areas/CellDropdown.vue
  packages/ui/vue/widget/table/pivot/src/components/Areas/CellsArea.vue
  packages/ui/vue/widget/table/pivot/src/components/Areas/ColumnsArea.vue
  packages/ui/vue/widget/table/pivot/src/components/Areas/MemberDropdown.vue
  packages/ui/vue/widget/table/pivot/src/components/Areas/RowsArea.vue
  packages/ui/vue/widget/table/pivot/src/components/PivotTable.vue
  packages/ui/vue/widget/table/pivot/src/index.ts
  packages/ui/vue/widget/table/pivot/tsconfig.json
  packages/ui/vue/widget/table/pivot/vite.config.ts
Labels: enhancement

#175 add Bbox and description to CuePoints
  packages/app/default/e2e/vue.spec.ts
  tools/test/screenshoter/screenshoter.ts
Labels: enhancement

#117 Add icon widget
  packages/ui/vue/widget/icon/package.json
  packages/ui/vue/widget/icon/src/IconWidget.vue
  packages/ui/vue/widget/icon/src/IconWidgetSettings.vue
  packages/ui/vue/widget/icon/src/assets/icon.svg
  packages/ui/vue/widget/icon/src/assets/output.json
  packages/ui/vue/widget/icon/src/index.ts
  packages/ui/vue/widget/icon/tsconfig.json
  packages/ui/vue/widget/icon/utils/parseJson.ts
  packages/ui/vue/widget/icon/vite.config.ts
Labels: enhancement

#232 Update docker-compose.yaml
  Docker/docker-compose.yaml
Labels: enhancement
